name: rago
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #
  ragotheme:
    path: ./packages/theme/ragotheme

  lottie: ^1.2.2
  flutter_svg: ^1.0.3
  flutter_feather_icons: ^2.0.0+1
  flutter_radio:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/gif/
    - assets/json/
    - assets/svg/
